PASS: Logic and Validation add methods in result unit tests
Amonov996/EssayAnalyzer pull request #45
Opened 2023-12-18 14:42 UTC by Ravshan9812

2023-12-18 14:48 UTC, josindarov reviewed
![image](https://github.com/azam-amonov/EssayAnalyzer/assets/94104009/64d7eca7-fc01-496d-ae3b-ba0dc36fd98f)
use just [Theory] instead of [Xunit.Theory]

2023-12-18 14:56 UTC, azam-amonov requested changes
### First of all!
- Before commit PASSED Test commit FAIL

2023-12-18 14:56 UTC, azam-amonov commented on EssayAnalyzer.Api/Services/Foundation/Results/ResultService.Exception.cs
> +                    new ResultValidationException(exception);
Make single line code on 
var resultValidationException =
                    new ResultValidationException(exception);

2023-12-18 14:56 UTC, azam-amonov commented on EssayAnalyzer.Api/Services/Foundation/Results/ResultService.Validaton.cs
> +                (Rule: IsInvalid(result.Feedback), Parametr: nameof(Result.Feedback)));
Add Validation Rule for EssayId

2023-12-18 14:56 UTC, azam-amonov commented on EssayAnalyzer.Api/Services/Foundation/Results/ResultService.Validaton.cs
> +        Message = "Id is required."
Remove dot (.) from message

2023-12-18 14:56 UTC, azam-amonov commented on EssayAnalyzer.Api/Services/Foundation/Results/ResultService.Validaton.cs
> +    };
Remove dot (.)  message

2023-12-18 14:56 UTC, azam-amonov commented on EssayAnalyzer.Api/Services/Foundation/Results/ResultService.Validaton.cs
> +
Remove empty line

2023-12-18 14:56 UTC, azam-amonov commented on EssayAnalyzer.UnitTest/Services/Foundation/Results/ResultServiceTests.Logic.Add.cs
> +    public partial class ResultServiceTests
Remove unused libraries, clean namespaces
![Uploading Screenshot 2023-12-18 at 19.51.39.png…]()

2023-12-18 14:56 UTC, azam-amonov commented on EssayAnalyzer.UnitTest/Services/Foundation/Results/ResultServiceTests.Logic.Add.cs
> +            broker.InsertResultAsync(inputResult))
Add Tab for second line

2023-12-18 14:56 UTC, azam-amonov commented on EssayAnalyzer.UnitTest/Services/Foundation/Results/ResultServiceTests.Validation.Add.cs
> +    public partial class ResultServiceTests
Make clean namespaces here
![Uploading Screenshot 2023-12-18 at 19.53.01.png…]()

2023-12-18 14:56 UTC, azam-amonov commented on EssayAnalyzer.UnitTest/Services/Foundation/Results/ResultServiceTests.Validation.Add.cs
> +
Add 
 invalidResultException.AddData(
                key: nameof(Result.EssayId),
                values: "Id is required.");

2023-12-18 14:56 UTC, azam-amonov commented on EssayAnalyzer.UnitTest/Services/Foundation/Results/ResultServiceTests.cs
> +{
Clean Namespaces

2023-12-19 07:21 UTC, azam-amonov approved these changes

2023-12-19 07:25 UTC, josindarov reviewed
![image](https://github.com/azam-amonov/EssayAnalyzer/assets/94104009/061e9acb-c524-4c60-b0db-0233fbe46aff)

Don't use just Exception as type of your method because it's not a service exception it is validation exception

2023-12-19 07:27 UTC, josindarov reviewed
![image](https://github.com/azam-amonov/EssayAnalyzer/assets/94104009/bca5ad41-cef4-4fe0-aa48-30658fe46636)

remove empty space in 22nd line

2023-12-19 07:56 UTC, josindarov approved these changes

2023-12-19 07:56 UTC, merged